// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9U75ma-TyiP7Gxnd9lX7fh3wmiJfWxm8',
    appId: '1:117178597527:web:d4af7d38302107804869d2',
    messagingSenderId: '117178597527',
    projectId: 'dsgo-jhlee',
    authDomain: 'dsgo-jhlee.firebaseapp.com',
    storageBucket: 'dsgo-jhlee.appspot.com',
    measurementId: 'G-NJDLGFJGZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3attVLZrPa1uPfBgCAKaNO317oKObZ4g',
    appId: '1:117178597527:android:c0e48ddecc1a067a4869d2',
    messagingSenderId: '117178597527',
    projectId: 'dsgo-jhlee',
    storageBucket: 'dsgo-jhlee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2ZA8kqOHORsDK6Ht3jDtvJYuxUaVk78',
    appId: '1:117178597527:ios:83282bb08aba58ba4869d2',
    messagingSenderId: '117178597527',
    projectId: 'dsgo-jhlee',
    storageBucket: 'dsgo-jhlee.appspot.com',
    iosClientId: '117178597527-6660nur4giv79s27kh3tdolpe8c5h5h0.apps.googleusercontent.com',
    iosBundleId: 'xyz.deokso.app.dsgo',
  );
}
